spring.application.name=GrowTogetherAPI
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/GrowTogether_DB
spring.datasource.username=root
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initial Data Loading
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
